### PR TITLE
Enhance README and add details about demo library configuration

### LINKED ISSUE #266: Please create documentation about how to deal with this tool
In a `README.md`

Part of the information are already available at https://wiki.openzim.org/wiki/Content_team#Demo_a_ZIM

### PR DESCRIPTION
**Pull request by benoit74**
Partial enhancement of #266 

Changes:
- drop codefactor badge which wasn't working (and I'm not sure it is really valuable on this repo)
- add few explanations about what we can find in this repo
- add a section about demo library configuration

### CODE REVIEW

**Review by rgaudin — APPROVED** [review]
I think the demo part should be in `zim/demo-library` but it works as well

**Comment by benoit74** [comment]
> I think the demo part should be in zim/demo-library but it works as well

I hesitated, but I felt it was a bit weird as well ; for someone who has no idea where to look, he will first read the main README where we would still need a "redirection" to zim/demo-library README which itself redirects to the wiki ... lot's of clicks ^^

**Comment by benoit74** [comment]
Please do not merge, see [last issue comment](https://github.com/kiwix/operations/issues/266#issuecomment-2384900878), this does not fulfill the expectations.

**Comment by kelson42** [comment]
> `zim/demo-library`

I agree and this is what I expected first regarding the "demo-library" feature specific documentation.

**Comment by benoit74** [comment]
> I agree and this is what I expected first regarding the "demo-library" feature specific documentation.

Expecting is easy. Opening clear issues and answering my questions / uncertainties seems harder. ^^ Now everything is clear and I will fix this.

**Pull request merged**
